encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path('', views.index, name='index'),
    path('wiki/<str:title>', views.view_entry, name='view_entry'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('edit/<str:title>', views.edit, name='edit'),
    path('random_entry', views.random_entry, name='random_entry')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encyclopedia/', include('encyclopedia.urls'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
import markdown2

from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django import forms

from . import util

class NewEntryForm(forms.Form):
    title = forms.CharField(label='Title', max_length=50)
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": 10, "cols": 50}))

# Create your views here.
def index(request):
    return render(request, 'encyclopedia/index.html', {
        'entries': util.list_entries()
    })


def view_entry(request, title):
    entry = util.get_entry(title)
    if not entry:
        raise Http404("Entry does not exist")
    return render(request, 'encyclopedia/entry.html', {
        'title': title,
        'entry': markdown2.markdown(entry)
    })
    

def search(request):
    query = request.GET['q']
    
    titles = util.list_entries()
    
    if titles.count(query) == 1:
        return HttpResponseRedirect(reverse(
            'encyclopedia:view_entry', args=[query]
        ))
    
    search_result = [title for title in titles if query in title]
    return render(request, 'encyclopedia/index.html', {
        'entries': search_result
    })


def create(request):
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            
            if util.get_entry(title):
                return HttpResponseBadRequest('<h1>The entry is already existed</h1>')
            
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse('encyclopedia:index'))
        else:
            return render(request, 'encyclopedia/create.html', {
                'form': form
            })
            
    return render(request, 'encyclopedia/create.html', {
        'form': NewEntryForm()
    })
    
    
def edit(request, title):
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        print(form)
        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse(
                'encyclopedia:view_entry', args=[title]
            ))
        else:
            return render(request, 'encyclopedia/edit.html', {
                'title': title,
                'form': form
            })
    
    form = NewEntryForm(initial={
        'title': title,
        'content': util.get_entry(title)
    })
    
    # Ensure the title cannot be changed
    form.fields['title'].widget.attrs['readonly'] = True

    return render(request, 'encyclopedia/edit.html', {
        'title': title,
        'form': form
    })
    
    
def random_entry(request):
    return HttpResponseRedirect(reverse(
        'encyclopedia:view_entry',
        args=[random.choice(util.list_entries())]
    ))

encyclopedia/templates/encyclopedia/create.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                <p>{{ field.errors }}</p>
                <div>{{ field.label_tag }}</div>
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Create New Entry">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                <p>{{ field.errors }}</p>
                <div>{{ field.label_tag }}</div>
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Save Change">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ entry|safe }}
    <a href="{% url 'encyclopedia:edit' title %}">Edit Entry</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:view_entry' entry %}">{{ entry }}</a>
            </li>

        {% empty %}
            <li>No entry</li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>